i18next/next-i18next

- src/hocs/app-with-translation.js
`getInitialProps` in Page will stop working if you deconstruction `pageProps`.
> bugfix: remove deconstruction for pageProps

- src/hocs/app-with-translation.js
By default react-tree-walker passes in an undefined context, which
breaks packages like Material UI and JSSProvider.  This fix passes
in an empty object for context, which fixes components that use the
legacy context API.
See
> Add context to react-tree-walker call

- __tests__/components/Link.test.js
- package.json
- src/components/Link.js
- yarn.lock
In the current usage, if a URL without a protocol and host is passed
into URL, 'http://localhost' will be added to the beginning of the
href (e.g. '/foo' will become 'http://localhost/foo').  This change
ensures that a URL without a protocol and host is preserved and
left without the protocol and host (e.g. '/foo' remains '/foo').
> Fix url.href in url-parse usage

- __tests__/config/create-config-non-node.test.js
- __tests__/config/create-config.test.js
- src/config/create-config.js
If a user specifies another defaultNS and we are client-side, then
config.ns will never be reassigned. This change properly sets the
ns key on the config object.
Resolves #64.
> Properly set namespace on client

- __tests__/utils/lng-path-corrector.test.js
- src/utils/lng-path-corrector.js
If `currentLanguage` is not in the `config.allLanguages` array, throw an error.
Resolves #65.
> Catch configuration error in lngPathCorrector

- __tests__/utils/console-message.test.js
- example/yarn.lock
- package.json
- src/config/default-config.js
- src/hocs/app-with-translation.js
- src/index.js
- src/utils/console-message.js
- src/utils/index.js
- yarn.lock
This enables users to set a strictMode boolean in their i18n config, that defines whether messages and errors are logged to the console.
So far I've not added an info message regarding traceLimit. I've added the `traceLimit` option because some errors would need a stack trace and that it's used in the function. Generally, the stack trace from pretty-error only contains standard modules and no helpful information, therefore it's quite unlikely that anyone would gain from being able to set the env variable. Nevertheless, I think, it does make sense to have it available.
> Add createConsoleMessage functionality + logging configuration

- __tests__/components/Link.test.js
We don't need i18n.languages anymore
> Removing dead code from test

- __tests__/components/Link.test.js
Adding tests to ensure that withNamespaces props are not passed on to Next's Link component.
Reference #97.
Resolves #101.
> Adding test to ensure removal of withNamespaces props

- src/hocs/app-with-translation.js
Sometimes, `Component.displayName` is not defined, causing our `namespacesRequired` warning to print `undefined`.  But we can fallback to `Component.name` instead.
As a final fallback, in the event that `name` and `displayName` are both `undefined`, just print 'Component'.
Resolves #112.
> Use Component.name if Component.displayName is undefined

- __tests__/components/Link.test.js
- __tests__/components/Trans.test.js
- __tests__/hocs/with-config.test.js
- src/components/Link.js
- src/components/Trans.js
- src/hocs/index.js
- src/hocs/with-config.js
- src/index.js
An example implementation of how we could use a higher-order component to pass configuration on to our React components that require configuration.
Ref #113.
> Adding HoC to handle passing config to React components

- README.md
- __tests__/create-i18next-client.test.js
- src/config/default-config.js
- src/create-i18next-client.js
I want to start a discussion about this feature
A while a go we were discussing custom language detectors and @isaachinman implemented the option to add plugins to next-i18next (https://github.com/isaachinman/next-i18next/commit/14d494fc0e871a509d4214d1523fa7cade33e13b).
However this was exclusively for plugins, which doesn't work with the custom language detectors interface provided by `i18n`.
Adding this feature makes it easier for users develop their own language detector and use it with the following interface and options:
Interface
```js
export default {
name: 'myDetectorsName',
lookup(options) {
// options -> are passed in options
return 'en';
},
cacheUserLanguage(lng, options) {
// options -> are passed in options
// lng -> current language, will be called after init and on …
```
> Add customDetectors option 

- __tests__/utils/lng-path-corrector.test.js
- src/hocs/app-with-translation.js
- src/utils/lng-path-corrector.js
We cannot use window.location.pathname in lngPathCorrector if the route is a custom route, since window.location.pathname !== router.pathname (instead, it is equal to router.asPath).  Since this is the case, [we cannot use shallow routing](https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/router/router.js#L374-L375) and a new page is requested, resulting in a 404 error whenever the i18n.changeLanguage function is invoked.
This commit changes appWithTranslation to instead use the withRouter Next HoC, which exposes a router prop.  The router prop has pathname, query, and asPath attributes which we can use instead of using window.location.pathname.  We then modify query and asPath in lngPathCorrector (as pathname will remain unchanged if we are only changing the language) …
> Refactor appWithTranslation to work with custom routes

- .babelrc
- .gitignore
- __tests__/config/create-config.test.js
- __tests__/hocs/with-config.test.js
- __tests__/middlewares/next-i18next-middleware.test.js
- __tests__/test-i18next-config.js
- __tests__/utils/console-message.test.js
- examples/simple/i18n.js
- middleware.js
- package.json
- src/components/Link.js
- src/config/create-config.js
- src/hocs/app-with-translation.js
- src/index.js
- src/middlewares/next-i18next-middleware.js
- src/utils/force-trailing-slash.js
- src/utils/lng-path-detector.js
- yarn.lock
After some further thought, I don't think `rollup` or `webpack` are truly necessary for a lib like this.
The primary consumer of this library are NextJs applications, which will have their own build process to compile both server and client code.
End users can modify their own Babel configuration to target whatever browsers they'd like.
In the end, we should primarily export `es` modules, but it's also useful to export `cjs` for those people who don't want to set up `es` modules for their NodeJs processes.
> refactor: Babel setup

- README.md
- __tests__/utils/lng-path-corrector.test.js
- __tests__/utils/lng-path-detector.test.js
- src/config/default-config.js
- src/utils/lng-path-corrector.js
- src/utils/lng-path-detector.js
- src/utils/locale-subpath-required.js
Add of variable **defaultLocaleSubpath** to let the user choose if he wants his default language in URL
Example: If the default language is **EN**, the url will be **/en/someUrl**
From https://github.com/isaachinman/next-i18next/pull/24
> feat: Enable default language subpath

- README.md
- __tests__/components/Link.test.js
- __tests__/config/create-config.test.js
- __tests__/config/test-helpers.js
- __tests__/hocs/with-config.test.js
- __tests__/middlewares/next-i18next-middleware.test.js
- __tests__/router/wrap-router.test.js
- __tests__/utils/lng-path-corrector.test.js
- __tests__/utils/lng-path-detector.test.js
- examples/simple/__tests__/e2e/basic.test.js
- examples/simple/__tests__/e2e/locale-subpaths-all.test.js
- examples/simple/__tests__/e2e/locale-subpaths-foreign.test.js
- examples/simple/next.config.js
- jest-puppeteer.config.js
- src/components/Link.js
- src/config/default-config.js
- src/hocs/app-with-translation.js
- src/middlewares/next-i18next-middleware.js
- src/utils/lng-path-corrector.js
- src/utils/lng-path-detector.js
- src/utils/locale-subpath-required.js
- types.d.ts
This changes the `localeSubpaths` config option from a boolean to an enum of strings: `none`, `foreign`, and `all`. We may add more options in the future (eg regional locales).
I've also added a new e2e test, and we're now covering each of these three `localeSubpaths` options with an e2e test.
Fixes #211.
> refactor: Change locale subpaths to a string enum

- types.d.ts
Type checking does not work bacause of return type `any` of a `withNamespaces` function.
Type casting helped, but it's not the correct behaviour:
> feat(types): add return type for withNamespaces function

- types.d.ts
The same issue as here: https://github.com/isaachinman/next-i18next/issues/220#issuecomment-471028160
But the merged code was removed later in https://github.com/isaachinman/next-i18next/pull/225/files
> fix(types): return Component type in appWithTranslation

- types.d.ts
- Removed `extends WithNamespaces`, let the developer uses his own types for the component. 
- Do not enforce developer to define I18n `t` function (removal of extends - e.g. `React.SFC<{myProp: string}>`)
- If the developer wants to use the `t` function in his Component, he has to set props with I18nProps interface (`React.SFC<I18nProps>`) or extend his own interface with I18nProps (`interface CustomProps extends I18nProps { myProp: string }`)
Now the typing works correctly:
```
yarn run v1.13.0
$ rimraf ./build && next build && tsc
Creating an optimized production build ...
> Using external babel configuration
> Location: "/Users/prokop/Sites/_yoyo/xoxo/.babelrc"
Compiled successfully.
┌ /
├ /_app
├ /_document
├ /_error
├ /principles
└ /signers
pages/index.tsx:21:10 - error TS2739: Type …
```
> fix(types): remove extends of WithNamespaces

- __tests__/config/create-config.test.js
- __tests__/config/test-helpers.js
- src/config/create-config.js
- src/config/default-config.js
In order to make it more explicit that users that define their own configurations will have to set their own `config.backend` options, moving the definition of `config.backend` to `default-config.js`.
Ref #140.
> refactor: Moving setting of config.backend to default configuration

- middleware.d.ts
- package.json
- yarn.lock
In order to setup _next-i18next_, we need to import the package's Express middleware creator function `import nextI18NextMiddleware from 'next-i18next/middleware'` and add the middleware to the express server: ` server.use(nextI18NextMiddleware(nextI18Next));` The middleware module misses the type definitions and TypeScript treats this import as `any`, so I added the definitions in the _middleware.d.ts_
> refactor: Added the TypeScript declaration file for the middleware module

- __tests__/utils/lngs-to-load.test.js
- src/hocs/app-with-translation.js
- src/utils/lngs-to-load.js
In order to support [locals resolving](https://www.i18next.com/principles/fallback#locals-resolving) feature from i18next we need to load the main language of the locale-specific initial language.
Here is the use case:
The website supports the `fr` language however there is a legal related copy that only apply to France.
By creating a folder `/locales/fr-FR` we can add these locale-specific copies in there and make i18next fall back to the general `/locales/fr` language for the keys that it doesn't find on the specific folder.
ps: I implemented this in a way that doesn't impact the current usage. So if you only use global languages ( `fr, en, de, etc..`) nothing changes.
> fix: Load main language when initial language is locale specific

- __tests__/config/create-config.test.js
Adding tests to achieve 100% unit test coverage for create-config.js.
> chore: 100% unit test coverage for create-config.js

- README.md
- __tests__/middlewares/next-i18next-middleware.test.js
- __tests__/utils/lng-path-detector.test.js
- examples/simple/server.js
- src/middlewares/next-i18next-middleware.js
- src/utils/lng-path-detector.js
If we perform a redirect in lngPathDetector (using localeSubpaths option), we do not want any subsequent processing of routes or middleware.  Thus, next() should not be called in our middleware if we redirect.  This change ensures that we do not process any further middleware or routes if we redirect in lngPathDetector.
Appropriate changes in unit and e2e tests have been made to ensure no regression occurs.
Additionally, documentation changes have been made to make it explicit that we may perform redirects within our middleware and, thus, the order in which you run our middleware is important.
Resolves #304.
> fix: Do not call next() after redirect

- types.d.ts
Fixes #345.
Removes imports which are non-existent since version 10 of react-i18next and uses the type for withTranslation directly from react-i18next.
> Types for react-i18next v10

- types.d.ts
If you use `next-i18next` with Typescript, typing `WithTranslation` is necessary for Props typing. The typing mainly includes the `t` function which is heavily used if you want to translate.
Re-exporting the typing from `react-i18next` would be cool because direct importing from this package isn't needed anymore. This causes higher updatability.
> feat: re-export type WithTranslation from react-i18next for single point of typing

- types.d.ts
Following up on the change in https://github.com/isaachinman/next-i18next/pull/361 ...
We also consume the types for `I18n` and `TFunction`. We currently have to import the `i18next` package, just to get a hold of these types. The version differences between `next-i18next`'s dependencies and ours regularly cause a type mess. This has also been requested in https://github.com/isaachinman/next-i18next/issues/375
Now that we made the first step towards re-exporting dependencies' types in the PR mentioned above, can we consider exposing these too? The reasoning is the same...
> Re-exporting the typing from `react-i18next` would be cool because direct importing from this package isn't needed anymore. This causes higher updatability.
Fixes #375
> feat: Re-export types I18n and TFunction from i18next

- __tests__/types.test.ts
- src/index.ts
- types.d.ts
I've got several errors
1. error TS2339: Property `appWithTranslation` does not exist on type `NextI18Next`
2. Cannot invoke an expression whose type lacks a call signature. Type `WithTranslation` has no compatible call signatures. e.g. `withTranslation(i18nextNamespaces),`
`appWithTranslation` should be exported from type `NextI18Next` as it's exported in implementation.
`WithTranslation` type might be as function and as object, it depends on what we are looking for.
> Fix: appWithTranslation / withTranslation typings

- package.json
- yarn.lock
Fix the following error when using WithTranslation interface 
```Property 't' does not exist on type 'Readonly<Props> & Readonly<{ children?: ReactNode; }>'.```
Typescript user need to be at least at version ``` 17.0.9``` from the README of the react-i18next library
https://github.com/i18next/react-i18next/blob/master/README.md#requirements
> fix: update of i18next and react-i18next version to fix typescript 

- README.md
- __tests__/middlewares/next-i18next-middleware.test.ts
- __tests__/test-i18next-config.ts
- src/config/default-config.ts
Lack of trailing slashes on the default config value for `ignoreRoutes` prevents loading of i18n for any routes that start with `/static`. Such as, for example: `my.blog.com/static-typing-is-cool`. This PR fixes this by adding trailing slashes.
Fixes #455.
> fix: add trailing slash to ignoreRoutes

- __tests__/config/create-config.test.ts
- __tests__/middlewares/next-i18next-middleware.test.ts
- src/config/default-config.ts
- tsconfig.json
> refactor: Use initImmediate in SSR

- __tests__/types.test.tsx
- src/index.ts
- types.d.ts
Fixes #360 
`WithTranslationHocType` is a new type that's used internally to type `withTranslation` HoC.It has been previously called `WithTranslation`.
That resulted in a name clash since `react-i18next` [exports its own `WithTranslation` interface](https://github.com/i18next/react-i18next/blob/master/src/index.d.ts#L69). This interface is the interface of the pros injected by `withTranslation` HoC (yes that naming is quite counter-intuitive). 
The issue was missed in the tests because the dummy component was not typed.
> fix: export `WithTranslation` props type for typescript

- __tests__/middlewares/next-i18next-middleware.test.ts
- src/middlewares/next-i18next-middleware.ts
This PR fixes #500 bug.
I've refactored middleware tests so the inner implementation won't be mocked.
It revealed an another bug, the `lng` query param is wrong when the page in one of the secondary langs
> fix(middleware): prevent removing subPath when not required

- README.md
Hello @isaachinman. 
I think that if you add an item about changing a `package.json`, it will be more clear.
I followed the instructions and inattentively read the description about [custom servers](https://github.com/zeit/next.js#custom-server-and-routing). And I could not understand why when using `localeSubpaths` my locale subpaths give a 404 error.
Thanks to your [article](https://medium.com/@isaachinman/creating-localised-nextjs-apps-with-next-i18next-f01d5e610307), everything is very clear and detailed there. It may be replaced by examples of code from your article instead of  links to files in the repository ([`_app.js`](./examples/simple/pages/_app.js), [`server.js`](./examples/simple/server.js) and [`I18n.js`]((./examples/simple/i18n.js))) in the README file.
Would you like me to …
> docs: Add item about changes to package.json

- examples/simple/pages/_app.js
[App Container Deprecated](https://github.com/zeit/next.js/blob/master/errors/app-container-deprecated.md)
- Removed the <Container> component from Custom <App> (./pages/_app.js).
> chore: Removed the <Container> component from Custom <App> (./pages/_app.js)

- src/utils/console-message.ts
> fix: Setting stackTraceLimit properly in createConsoleLog

- types.d.ts
Fix [#574](https://github.com/isaachinman/next-i18next/issues/574).
It was caused by this breaking change in typescript 3.7 
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#local-and-imported-type-declarations-now-conflict
If the `skipLibCheck` in tsconfig.json is `false`, the compile-time error `Import declaration conflicts with local declaration of 'WithTranslation'.` will be thrown.
> fix: Typescript declaration conflict error

- __tests__/create-i18next-client.test.ts
- __tests__/types.test.tsx
- examples/simple/server.js
- examples/simple/yarn.lock
- src/create-i18next-client.ts
- src/index.ts
- types.d.ts
Adds an `initPromise` property to the NextI18Next class which can then be awaited if desired:
```jsx
await nextI18next.initPromise
server.use(nextI18NextMiddleware(nextI18next))
```
Fixes #564.
> feat: Add initPromise to NextI18Next class

- README.md
It's a trap for new users. It is not immediate [in Next official doc for custom app](https://nextjs.org/docs/advanced-features/custom-app) that we need to add `getInitialProps` for i18n, all the more that it disable automatic static optimization (it frightens beginners to uncomment the code :) )
> docs: explicit the need for `getInitialProps` for stateless app

- src/index.ts
fixes #606.
There are others who have requested it plus i18next does work without such a check - why a library/plugin like next-i18next would add such a "validation" without a real need doesn't make much sense to me. 
Anyhow, simple to fix. Thanks for making next-i18next 🙂
> feat: allow config.otherLanguages to be empty

- package.json
We currently use this package within a package that is consumed by our applications through a shared runtime package (fig 1). Therefore our applications are not fond of `express` or `next` and don't include any types. 
During the build process, Typescript will throw an error (fig 2) saying it can't find the types of `express` and advises us to install them.
```
// fig 1
// simplified dependency tree w/o node_modules/ directory
app-one
└── next-runtime
└── our-i18n-lib/
└── next-i18next
app-two
└── next-runtime
└── our-i18n-lib/
└── next-i18next
```
```
// fig 2
../../../node_modules/next-i18next/types.d.ts:11:25 - error TS7016: Could not find a declaration file for module 'express'. '/.../app-one/node_modules/express/index.js' implicitly has an 'any' type.
Try `npm install @types/express` …
```
> chore: move @types/express to dependencies

- README.md
i wax trying to use next-i18next with a project i was working on but couldn't quite get locale subpaths working properly 
after some investigation it turns out i had nextjs version 9.3 which doesnt support rewrites and that took me quite a while to notice
So i added extra information to the read me to prevent others from falling in the same pitfall
> docs: Add required Next.js version to README

- README.md
- TYPESCRIPT.md
Additional examples should be added, such as how to type a page that requires additional props beside the t function.
> feat: Add a TypeScript usage section to the README

- package.json
- types.d.ts
- yarn.lock
I18nContext is exported as type instead of
value, typescript would complain when it is
used as value.
This commit:
- manually creates the type for context and export it
as upstream `react-i18next` also has incorrect types
- export `withTranslation` as it is exported in index
- add a demo page for I18nContext in example
Fix #789
> fix: I18nContext exported as type

- src/config/create-config.ts
Setting fallback language to defaultLanguage in production should only occur if the developer didn't specifically set it to `false`, since that would be a valid config for i18next.
This fix will make it possible to avoid loading any fallback translation files, which could speed up page load.
> fix: allow fallbackLng to be set to false

- package.json
- src/appWithTranslation.tsx
- types.d.ts
- fixes #907 by exposing `appWithTranslation` type
- changes `appWithTranslation` type signature: param is a React Component, not a React Component instance
~~- adds a Next.js example to typescript~~
- fixes the `run-example:prod` script by adding the `build` step before it
> fix: TS issues for v8-beta

- src/config/createConfig.ts
- src/config/defaultConfig.ts
- src/utils/index.ts
- src/utils/isServer.ts
- tsconfig.json
This PR allowing tree-shaking to work on client / server bundles using [`process.browser`](https://github.com/vercel/next.js/blob/58ea3bb47966ba7ae0f12a9267b54f79a5b4c9fc/test/unit/next-babel-loader.unit.test.js#L124) which is an env variable that gets replaced by next build.
Before, (client bundle)
After, (client bundle)
In the `after` image you can see that `createConfig` function is much smaller & optimized.
> fix: Remove server side code from client bundle

- src/config/create-config.ts
> Make create-config defaultFile use localeStructure

- types.d.ts
Currently, the ts definition lacked the `Trans` component. I added the import from `react-i18next`.
> fix: added Trans to TS definition v8-beta

- package.json
- src/appWithTranslation.tsx
- src/serverSideTranslations.ts
- yarn.lock
Uses [serialize-javascript](https://www.npmjs.com/package/serialize-javascript) to stringify a user's i18next config, which may contain primitives (like functions) that NextJs will refuse to serialise out of the box.
The config gets serialised in `serverSideTranslations`, and then reparsed in `appWithTranslation` via `Function()`.
This allows us to maintain a `next-i18next.config.js` file, without requiring the user to import it themselves, or pass it as arguments into any of `next-i18next`'s functions.
Fixes #931.
> refactor: Use serialize-javascript

- src/config/createConfig.test.ts
- src/config/createConfig.ts
> fix-848: Deep merge options.backend

- .circleci/config.yml
- cypress/integration/basic.e2e.ts
- package.json
- src/createClient/browser.ts
- yarn.lock
> refactor: Remove i18next-http-backend

- src/appWithTranslation.tsx
- src/index.tsx
- types.d.ts
> refactor: Add globalI18n

- .npmignore
- package.json
- serverSideTranslations.d.ts
- src/appWithTranslation.tsx
- src/config/createConfig.test.ts
- src/config/createConfig.ts
- src/createClient/browser.ts
- src/createClient/node.ts
- src/serverSideTranslations.test.ts
- src/serverSideTranslations.ts
- src/types.ts
- yarn.lock
By using typescripts declaration mode we can generate d.ts files for all of the relevant types and stop shipping the /src directory
fix for https://github.com/isaachinman/next-i18next/issues/1026
> fix: generate types using tsc and stop shipping the /src directory

- examples/simple/next-i18next.config.js
- src/createClient/node.test.ts
- src/createClient/node.ts
With the current implementation i18next is initialized on each request on server side.
This triggers a backend load each time.
When using "external" backend plugins via `.use()` this will generate unnecessary load and traffic, i.e. when using i18next-http-backend or i18next-locize-backend.
This PR tries to imitate the "old" behaviour done by i18next-http-middleware, like here: https://github.com/i18next/i18next-http-middleware/blob/master/lib/index.js#L39
where the i18next instance was cloned on each request, this way no unnecessary backend fetch was done.
> fix: prevent loading translations on each request

- package.json
- yarn.lock
The `@babel/plugin-transform-runtime` needs the dependency `@babel/runtime` in production, as stated in https://babeljs.io/docs/en/babel-plugin-transform-runtime. Because of that, Yarn v2 PnP complains when next-i18next is used in a NextJS project and gives the following error:
```
Module not found: next-i18next tried to access @babel/runtime, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: @babel/runtime (via "@babel\runtime\helpers\defineProperty")
```
The required dependency  `@babel/runtime` was added in package.json to resolve that.
To test the change, I ran the `examples/simple` project after installing, and it worked well.
Closes #1079
> build: install @babel/runtime to satisfy dependency of @babel/plugin-transform-runtime

- src/serverSideTranslations.test.ts
- src/serverSideTranslations.ts
`i18n.getFixedT` should return`t` function that defaults to given language, but the returned `t` function always returns the translation of the currently selected locale.
Issue details: https://github.com/isaachinman/next-i18next/issues/1184
Only the translation of default/current locale is being passed to the client.
Pass translation for all locales to the client, so `i18n.getFixedT` has the translation for the given language.
> fix: i18n.getFixedT to return correct t function

- src/types.ts
Export the `Resources` and `DefaultNamespace` types from `react-i18next` to allow for proper typing of the `useTranslation` and `serverSideTranslations` functions as described on [react-i18next documentation](https://react.i18next.com/latest/typescript) 
I've added documentation, but I'm not sure that is the better place for it.
> fix: Export Resources and DefaultNamespace from typings

- src/config/createConfig.test.ts
- src/config/createConfig.ts
Resolves #1250 
Since the `ns` option can be either a `string` or `string[]` ([docs ref](https://www.i18next.com/overview/configuration-options)) I am just checking for `combinedConfig.ns` to be defined before assigning `[defaultNs]`.
I've added a couple of tests as requested.
> fix: client config ns assignment logic

- src/serverSideTranslations.test.ts
- src/serverSideTranslations.ts
> fix: only import default config if no userConfig is passed

- src/config/createConfig.test.ts
- src/config/createConfig.ts
Using a different i18next backend having the same backend options like i18next-http-backend is currently causing the custom backend default options to be ignored.
With this fix, the addPath and loadPath options are only configured, if there is no custom backend.
> fix: set client side backend options only if there is no custom backend

- src/config/createConfig.test.ts
- src/config/createConfig.ts
Fixes #1090 by respecting any custom `interpolation.prefix` and `interpolation.suffix` while using `localeStructure` to see if the default namespace file exists.
Can be tested by changing `/examples/simple/next-i18next.config.js` to
```
module.exports = {
i18n: {
defaultLocale: 'en',
locales: ['en', 'de'],
},
interpolation: {
prefix: '%{',
suffix: '}',
},
localeStructure: '%{lng}/%{ns}',
}
```
Before the change, this config would result in this error:
```
Error: Default namespace not found at public/locales/%{lng}/%{ns}.json
```
After the change, the error goes away and interpolations work as expected. (To verify that interpolations work, you need to change `/examples/simple/public/locales/en/common.json` to use the `%{` `}` prefix and suffix.)
> fix: Respect user-defined prefix/suffix when looking for default NS

- docs/v8-migration.md
Resolves https://github.com/isaachinman/next-i18next/issues/1295
Preview: https://github.com/natterstefan/next-i18next/blob/chore/202107-v8-migration-guide/docs/v8-migration.md
> chore: removed compatibility with getInitialProps info in migration guide

- docs/v8-migration.md
Minor copy/paste error that I've came across while migrating a project to Version 8 of this package.
> docs: Fix typo in migration doc

- src/appWithTranslation.client.test.tsx
- src/appWithTranslation.server.test.tsx
- src/appWithTranslation.tsx
- src/serverSideTranslations.test.tsx
- src/serverSideTranslations.ts
- src/types.ts
* Memoize the i18n client and do not re-create it unless the route or
locale has changed (fix #1059).
* Let Next's router locale take precedence over initialLocale.
> fix: better support for shallow route changes

- src/appWithTranslation.tsx
Add support for proper custom App component types
fix #1348
> fix: Make appWithTranslation generic over AppProps type

- src/config/createConfig.test.ts
- src/config/defaultConfig.ts
Fixes #1255
cc @adrai – following up on your comment: https://github.com/isaachinman/next-i18next/issues/1255#issuecomment-864523329
We are already awaiting the initialisation promise inside `serverSideTranslations` [here](https://github.com/isaachinman/next-i18next/blob/e97bfbf4bfb3d3c8660a53018e40cf6e0cfd6865/src/serverSideTranslations.ts#L77).
The reason you have to manually list your namespaces in your demo project [here](https://github.com/locize/next-i18next-locize/blob/main/next-i18next.config.js#L17) is because they are not present in your filesystem, which we normally [query for automatically](https://github.com/isaachinman/next-i18next/blob/e97bfbf4bfb3d3c8660a53018e40cf6e0cfd6865/src/config/createConfig.ts#L120).
Let me know if you think this looks like a safe change 👍
> refactor: Set config.react.useSuspense to false

- README.md
Added a small note that might help resolve the communication for people deploying on Netlify / Vercel with `serverSideTranslations`. This issue seems to be brought up quite often so adding a note might help mitigate a small portion of those who do use the README.md
> chore: added note for vercel/netlify using serverSideTranslations

- src/index.tsx
- src/types.ts
These changes export the [react-i18next Translation component](https://react.i18next.com/latest/translation-render-prop) from the next-i18next module. I found this component the best match for introducing translations in the [Page.getLayout]( https://nextjs.org/docs/basic-features/layouts#per-page-layouts) function. The useTranslation hook is [not allowed because the getLayout function is not top-level](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level).
I also added test coverage for the Translation component by using it on the second page to render the header. It's tested by `yarn test:e2e`.
> feat: Expose Translation react-i18next component

- README.md
It took me a while to figure out how to get a custom interpolation prefix/suffix to work.
I think it's a little unintuitive that changing an option that relates to how the text inside the translation files is structured has a knock-on effect to how files are loaded. That is not criticism, I realize it's because of how the various packages interact, but it's still a bit of a head-scratcher.
After doing some digging, I came across #1090 that clarifies the issue, but I feel it's worth putting this in the README.
This PR does that. It's not much, but I hope you find it useful.
> docs: Clarify config for custom interpolation suffix/prefix

- src/appWithTranslation.client.test.tsx
- src/appWithTranslation.tsx
This PR will fix the Next/Link app unmount.
I placed the locale in a state instead of a variable, which fixes locale getting set to null.
The state will only change if the `initialLocale` has changed and is not equal to the current state and is not null.
Fixes #1628
> fix: appWithTranslation useMemo bug (null locale)

- vercel.json
Every merged PR in this repo triggers an extra GitHub notification. This happens because Vercel bot comments on the merge commit:
This PR silences Vercel bot, so it will no longer leave comments. Release previews are still accessible for PRs:
We are using this setup in [blockprotocol/blockprotocol](https://github.com/blockprotocol/blockprotocol) and it reduces notification spam quite substantially! 🙂
Docs: https://vercel.com/support/articles/how-to-prevent-vercel-github-comments
Feel free yo close this PR if you see downsides in the idea.
> chore: Mute vercel bot

- README.md
Hi! I just wanted to propose a small update to README.
After a bit of fiddling I realized, `transKeepBasicHtmlNodesFor` is under `react` key so wanted to include the link to the docs from here since i18next docs are separated from the one for react-i18next.
> feat: Link to react-i18next config options

- README.md
- src/serverSideTranslations.test.tsx
- src/serverSideTranslations.ts
I was running into an issue where `getFixedT` always returned values in the current language not the requested language. I found  this issue - https://github.com/i18next/next-i18next/issues/1184 about it. The fix for it was merged in and released and seemed to work. However a bit later the fix got reverted as people did not expect all locales to be loaded by the library. See the following issue - https://github.com/i18next/next-i18next/issues/1267.
This PR proposes a potential new argument to the `serverSideTranslations` function (could also be a config override field really). This argument can be used to provide extra locales to load for the specific page and allows one to opt into loading more or all locales. As a result `getFixedT` will then work for the locales that are loaded for the …
> Fix getFixedT function always returning values in current language

- src/appWithTranslation.server.test.tsx
- src/config/createConfig.test.ts
- src/config/createConfig.ts
- src/serverSideTranslations.ts
- src/types.ts
We currently have the use case to provide multiple locales (`de`, `de-AT`, `de-DE`, `de-CH`) for one language (`de`) without the need for individual translations. Preferably we would like to use a function for `fallbackLng`, like `(code) => code.split('-')[0]`, as we need to support a wide range of locales.
When using `fallbackLng` like this, we still need to provide JSON files for each locale, although the translations for `de-AT` are no different than for `de`. This PR is an attempt to fix this and I think it is related to https://github.com/i18next/next-i18next/issues/1652, https://github.com/i18next/next-i18next/discussions/1649 and https://github.com/i18next/next-i18next/issues/1465.
Depending on the setup, the changes of this PR might add multiple fallback locales to …
> Improve fallback language handling

- README.md
- src/config/createConfig.test.ts
- src/config/createConfig.ts
- src/serverSideTranslations.test.tsx
- src/serverSideTranslations.ts
- src/utils.ts
This PR adds support for `nonExplicitSupportedLngs` and is related to #1412. This features adds the possibility to support multiple variants of a language (`de-AT`, `de-CH` and `de-DE`) with a single JSON file (e.g. `public/locales/de/common.js`).
During the work on this PR I noticed that the the `default` value in `fallbackLng` should always be loaded. At least this is how I interprete this [testcase](https://github.com/i18next/next-i18next/pull/1930/files#diff-c87087f0d6c0b23943183ea270e1b1926cdf23e8bc7b7ae013762816561db596L152). Although this is related to #1927, the fix is part of this PR, because `nonExplicitSupportedLngs` depends on the same logic. Regarding the test-case above: I added `en-US` to supported `locales` and removed `en` from the `initialI18nStore`, because I think this …
> Add support for nonExplicitSupportedLngs

- src/serverSideTranslations.test.tsx
- src/serverSideTranslations.ts
Fixes #1941
I did not understand why the `existsSync` mock returns `false` on the first call for all test cases in `serversideTranslations.tests.tsx`. Maybe it is related to #1302 and therefore obsolete? I have changed it to always return `true`, but since this change effects all tests, I'm not sure if this is the intended behaviour.
Additionally, it might make sense to "enable" server-side environment for all tests with something like
```
beforeAll(() => {
Object.assign(process, { browser: false })
delete (global as any).window
})
```
as is already the case for `createConfig.tests.tsx`. Currently `createConfig` is running in "client.side mode", which may not be the desired behavior for testing `getServerSideTranslations`? If this sounds reasonable to you @adrai, I can add changes to this …
> Fix fallbackLng if namespaces are undefined

- .github/workflows/ci.yml
- .size-limit.cjs
- package.json
I'd like to rework the (dual) packaging if possible. That is a continuation of https://github.com/i18next/next-i18next/pull/1966#issuecomment-1285449857.
But before of that, I would like to ensure I have a correct baseline. So I introduced few things
- a github action
- a size-limit script (with webpack to follow possible tree-shakability regressions)
- an ecmascript check (to prevent regressions in the build)
The size-limit might obsolete in bundlesize, I might remove later on.
Locally
```bash
npm install
npm run build
npm run check-size
npm run check-dist
```
Want to analyze the differences in bundles (esm, cjs):
```bash
npm run analyze-size
```
Will open the 
We can already see that cjs does not tree-shake. Big opportunity cause by default nextjs will use it rather than esm.
> QA improve checks

- .github/workflows/ci.yml
Will avoid triggering twice the new gha workflow.
setup/node won't work yet as it lacks the lock file. It will be tackled in https://github.com/i18next/next-i18next/pull/1970
> CI fix github action event trigger

- .github/workflows/ci.yml
- .size-limit.cjs
- package.json
I know we already have bundlesize, but I'd like to expand the size-checks to the example app with size-limit. I'd like to have fine grain control on side-effects of publish improvements.
Same method used as in https://github.com/i18next/next-i18next/pull/1969
Running 
```bash
npm run check-size
```
Will give
> chore(size-limit): check also for next-app dist folder

- CHANGELOG.md
- package.json
I'd like to bump the minimum node version to 14.x (12.x is not maintained).
I feel it might avoid issue if this PR is merged: https://github.com/i18next/next-i18next/pull/1973
Next major version (13). 
Makes sense to merge along https://github.com/i18next/next-i18next/pull/1966  as both will bump a major.
I've been pretty lax on version (<14). In practice, I would recommended 14.13.1 minimum. But it's fine to not enforce it. (this helps when moving to pure esm)
> Drop node 12 support (next major)

- examples/simple/pages/second-page.tsx
- examples/simple/types.d/react-i18next.d.ts
I'd like to add type augmentation in the simple example.
That might help to detect anomalies when upgrading to react-i18next 12 / i18next 22. Cause the usage will slightly change. 
I'll be happy to include the changes when working on https://github.com/i18next/next-i18next/pull/1966.
> feat(example): add type augmentation for dictionnaries

- CHANGELOG.md
- package.json
For next major, I suggest to drop those.
I've upgraded react to 17 to align with nextjs 12.0.0 - https://github.com/vercel/next.js/blob/8a450db14a1b29d506ec86df1a002bc525ab0da7/packages/next/package.json#L117
> Drop support for nextjs < 12 and react < 17.0.2

- src/appWithTranslation.server.test.tsx
- src/appWithTranslation.tsx
- src/serverSideTranslations.test.tsx
- src/types.ts
This PR updates the appWithTranslation generic type to fit what is sent in by the consumers of the library.
It also updates _nextI18Next in SSRConfig to be nullable, which it may be in the case of not calling serverSideTranslations in the page.
The inverse, which is how it is today, would mean that appWithTranslation **always** would get a _nextI18next prop, which is not guaranteed, as indicated by the various null checks and errors thrown.
This fixes #1944
> fix: Fix types for appWithTranslation

- .github/workflows/ci.yml
Fix debug runner step and output examples/simple output.  
Why needed ? 
- test-e2e works on ci, not on my local machine. without lock file (choice made before), I'd like to exclude resolutions problems (reproducibility).
In the future I feel we would benefit to commit lock files (or at least for the base package).
See output in https://github.com/i18next/next-i18next/actions/runs/3410769134/jobs/5674130702
> ci: fix debug runner step

- package.json
I'd like to remove bundlesize. Why ?
- We introduced size-limit (and npm run check-size in the https://github.com/i18next/next-i18next/pull/1969 and subsequent PR's). I feel it's an easier tool.
- Bundlesize is relying on itorb (node-gyp), this makes install slower as it has to be compiled for no so much benefits (minus 15 seconds in install). 
- I also separate check-size from test-e2e. (I feel it's clearer IMO, but open any changes here)
```
npm why iltorb
iltorb@2.4.5 extraneous
node_modules/iltorb
iltorb@"^2.4.3" from brotli-size@0.1.0
node_modules/brotli-size
brotli-size@"0.1.0" from bundlesize@0.18.1
node_modules/bundlesize
```
> chore: remove bundlesize in favour of size-limit

- examples/simple/package.json
- examples/ssg/package.json
Due to a regression in swcMinify in nextjs 13.0.3, our (e2e) size limit checks fail. See https://github.com/vercel/next.js/issues/42813
The issue have since been fixed but not released.
As we don't use lock for examples, it's difficult to avoid having that issue to pop up from time to time (making the ci fail for no *real* reason). I locked the versions of nextjs (till we have better solution). good tradeoff
> chore(examples): lock nextjs version

- UPGRADING.md
In the light of https://github.com/i18next/next-i18next/discussions/2029.
@adrai I would like to release the v13.0.0, what's your feeling about it ? 
PS: The only thing was: https://github.com/i18next/next-i18next/pull/2018#issuecomment-1313565603 but I guess we can go on.
> Upgrading: clarify keys typings update

- package-lock.json
Lock wasn't refreshed. Now done.
PS: in my experience there's no "easy" way to ensure this with npm in the ci action (`npm ci` + node 14+16+18 and cache). I'll see what I can do later on. PNPM/Yarn3+ clears that out (see also https://github.com/belgattitude/compare-package-managers).
> chore(lock): freshen

- .github/workflows/ci.yml
Attempt to allow PR from forks to run workflows after synchronization.
When approved workflows runs from forks, but any subsequent commits does not trigger workflows anymore. Let's try https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
Example: https://github.com/i18next/next-i18next/pull/2025#issuecomment-1329335943
First commit after approval
Subsequent commits:
> ci: run workflow on forks

- examples/simple/package.json
- examples/ssg/package.json
A small update and alignment of deps for simple example
**Warning**
There's an issue regarding latest i18next. So I locked it to 22.3.0
> fix(example): align nextjs version and update

- CHANGELOG.md
- examples/simple/package.json
- examples/ssg/package.json
- package-lock.json
- package.json
A bug regarding key typings haven introduced in i18next v22.4.0. It's now fixed in latest `^22.4.3` (upstream dep)
- See https://github.com/i18next/i18next/issues/1859#issuecomment-1346177482
- See https://github.com/i18next/i18next/issues/1881
If you are experiencing errors such as `TS2746: This JSX tag's 'children' prop expects a single child of type 'ReactI18NextChild | Iterable ', but multiple children were provided.`...
..simply ensure i18next is at version `^22.4.3` in your package.json and run install.
> Examples updated to latest i18next

- src/types.ts
As discussed with @adrai here: https://github.com/i18next/next-i18next/issues/2060
> Fix default namespace import

- README.md
- src/serverSideTranslations.ts
To solve issues like this one: https://github.com/nrwl/nx/discussions/4983, and to not create hacky functions I suggest the following change.
It doesn't break anything but it adds the ability to set the default config path.
It will allow you to simply use the package in NX monorepo with the changes from the `dynamic path` example.
> feat(server-side): custom default config path

- src/config/createConfig.test.ts
- src/config/createConfig.ts
Fixes #2099 
As always, thanks for your hard work on this open source library. It's been an amazing benefit, many kudos 🙇 
This PR updates the library to allow interpolation affixes to be configured without setting the `localeStructure` field. This will improve developer experience and simplify user defined config.
If a manual `localeStructure`	 is provided, the user will need to ensure it conforms to their custom affixes.
> fix: allow user provided affixes to be used without providing localeStructure

- src/serverSideTranslations.ts
Thanks for developing a great library!
The `useTranslation` function completes the namespace defined in `CustomTypeOptions` on `i18next.d.ts`, but the `serverSideTranslations` function does not, so I changed the type.
(If the change causes any inconvenience, close this PR.)
> Update serverSideTranslation args type

- src/serverSideTranslations.ts
#2097 change was incorrect. Sorry about that.
At this time (v13.2.0), we ended up with the same type information as before we merged #2097, so we fixed that.
> fix serverSideTranslations args

- CHANGELOG.md
@adrai just a quick addition to help. 
I'll do in a different PR:
> docs: improve changelog

- src/serverSideTranslations.ts
Fixes #2201 
`Namespace` is not extending `Array` but `ReadonlyArray` so `ArrayElementOrSelf<Namespace>` is evaluated to `(readonly string[])[]` instead of `string[]`.
> fix: correct namespacesRequired type in serverSideTranslations

- src/appWithTranslation.client.test.tsx
- src/appWithTranslation.tsx
- src/utils.ts
This PR changes how next-i18next loads resources on page or locale change.
Instead of creating a new instance on page or locale change, the change uses [`addResourceBundle`](https://www.i18next.com/overview/api#addresourcebundle) method to load newly changed resources if instance was already created.
I made this change because I found an edge-case:
1. Enter page with `getStaticProps` and `serverSideTranslations` configured.
2. Move to page without `serverSideTranslations`, instead load translations in client-side with i18next-http-backend;
Also I used `suspense` option to `true`
3. Component with `useTranslation` hook got suspended, and it suspends forever because i18next instance is created repeatedly, thus not initialized forever.
After applying this patch, the infinite suspending issue …
> refactor: reuse existing instance

- README.md
Updated README to explain the best way to solve an [issue](https://github.com/i18next/next-i18next/issues/2259) where React state is getting cleared between page client-side navigation.
> doc(issue-2259): Document react state issue

- examples/simple/components/Header.tsx
- examples/simple/pages/index.tsx
- examples/simple/public/app.css
Thank you for your pull request. Please provide a description above and review
the requirements below.
Bug fixes and new features should include tests.
-->
Before: - 
After: -
> add features and responsive 

- package-lock.json
- package.json
This pull request moves the "@types/hoist-non-react-statics" package from the dependencies section to the devDependencies section in the package.json file. This change is appropriate because type declaration files are typically used during development and compilation but are not required at runtime.
The modification ensures that the type definitions for "hoist-non-react-statics" are available during development and TypeScript compilation, but won't be included in the production build of projects using this package. This change helps to reduce the size of the production bundle and follows best practices for managing dependencies in TypeScript projects.
To implement this change, I used the following npm command:
npm install @types/hoist-non-react-statics --save-dev
This command installs the …
> Move @types/hoist-non-react-statics to devDependencies"

- package-lock.json
- package.json
Fixes #2315
Reverts #2310
---
From #2310:
> type declaration files are typically used during development and compilation but are not required at runtime.
This is generally true, however `next-i18next` actually relies on types from `hoist-non-react-statics` which are exposed to the user:
https://github.com/i18next/next-i18next/blob/fe1b79a596f269bca9410d00e340e2dcfb633db0/src/appWithTranslation.tsx#L2
https://github.com/i18next/next-i18next/blob/fe1b79a596f269bca9410d00e340e2dcfb633db0/src/appWithTranslation.tsx#L129
If types are not included when installing the library, users will experience types errors, 
that might be hidden if `skipLibCheck` typescript compiler option is set to `true` (like in #2315).
---
If you don't want that `@types` package is always installed you should use …
> types: re-add `@types/hoist-non-react-statics` to dependencies
