- src/middlewares/next-i18next-middleware.js
> preserve original querystring parameters by appending them with lng

- __tests__/utils/force-trailing-slash.test.js
- __tests__/utils/lng-path-detector.test.js
- src/utils/force-trailing-slash.js
- src/utils/lng-path-detector.js
> Change preference approach to language/subpaths

- example/__tests__/e2e/e2e.test.js
Adding test cases to test switching back to first page using link in second page and adding test to change locales.
> Adding a few more e2e tests

- __tests__/components/Link.test.js
- src/components/Link.js
> Properly parse href in Link when it's an object

- src/hocs/app-with-translation.js
This PR fixes the issue that I described on issue #135.
I took a different approach because by cloning the instance I introduced some memory leak to my application to a point that the kubernetes pod were dying.
So the solution on the issue is not reliable, instead I'm making next.js serialize the server instance and using it if it is available.
I'll deploy this change tomorrow at work and keep an eye in our server's resources to see how it behave.
But it fix the problem.
For now I'm opening a PR to start a discussion and fix any comment if needed
> Serialize i18n instance and pass it through getInitialProps

- __tests__/components/Link.test.js
- src/components/Link.js
Ref [this comment](https://github.com/isaachinman/next-i18next/pull/149#issuecomment-459787337) in #149.
> Utilize lngPathCorrector within Link component

- src/config/create-config.js
- src/config/default-config.js
> feat: Deep merge nested config options

- examples/custom-routing/server.js
- examples/simple/__tests__/e2e/basic.test.js
- examples/simple/__tests__/e2e/locale-subpaths.test.js
- examples/simple/i18n.js
- examples/simple/index.js
- examples/simple/next.config.js
- examples/simple/package.json
- examples/simple/server.js
- examples/simple/yarn.lock
- jest-puppeteer.config.js
- package.json
> feat: Multiple e2e tests with different config options

- examples/custom-routing/i18n.js
> chore: Fix custom routing example

- package.json
- types.d.ts
I've added types for the module class.
> feat: Add typescript types

- .babelrc
> refactor: Transpile CJS to NextJs default target

- examples/simple/README.md
> chore: Add README to simple example

- types.d.ts
This commit allows to pass the App props to the `appWithTranslation` HOC.
+ More strict types for `localeSubpaths` config option
> feat(types): Improve TS types

- README.md
Change `clientside` to `client-side` .
> docs: Change clientside to client-side

- types.d.ts
Resolves https://github.com/isaachinman/next-i18next/pull/239#issuecomment-473892273
See [definition of `i18next InitOptions`](https://github.com/i18next/i18next/blob/19b2785206b1024497dab78e8ee6c1fb9dd90472/index.d.ts#L156)
cc @felixmosh
> fix(types): Extend config with options from i18next

- types.d.ts
> fix(types): remove T from return types

- types.d.ts
I have a problem with typescript error because I use allLanguages and defaultLanguage key from config when I generate the sitemap.
> fix(types): Add config to NextI18Next declaration

- README.md
> docs: Update docs to clarify existing i18next paradigms

- README.md
- __tests__/config/create-config.test.js
- __tests__/config/test-helpers.js
- src/config/create-config.js
- src/config/default-config.js
General cleanup of the config creation procedure.
Fixes #257, #294, and #297.
> refactor: Add localeExtension config option and clean up config procedure

- __tests__/utils/console-message.test.js
Some tests were testing to ensure that the function returns undefined, but it always returns undefined.  Changed them to test whether or not console methods were called instead.
Also, adding tests to get to 100% unit test code coverage.
> chore: updating console-message.js tests

- __tests__/utils/lng-from-req.test.js
Adding tests to achieve 100% unit test coverage for lng-from-req.js.
> chore: 100% unit test coverage for lng-from-req.js

- README.md
> docs: Add note to README about serverless

- src/index.js
> feat: Add useTranslation

- types.d.ts
This PR adds the typings of `useTranslation` to the `types.d.ts` for better dev experience and typescript support :)
> feat: Update types.d.ts with useTranslation

- __tests__/components/Link.test.js
- src/components/Link.js
> fix: Link no longer passed props.lng with react-i18next v10

- __tests__/config/create-config.test.js
- __tests__/config/test-helpers.js
- src/config/create-config.js
> feat: Validate defaultNS exists via fs

- package.json
- yarn.lock
> fix: Upgrade react-i18next to v10.11.3 to fix fs isClone bug

- package.json
- src/index.js
- yarn.lock
> fix: Update Babel deps and use core-js

- src/utils/lng-path-detector.js
> fix: Root path redirect for localeSubpaths

- examples/simple/yarn.lock
- src/hocs/app-with-translation.js
> refactor: Use router.replace after every lang change

- __tests__/types.test.ts
- src/index.js
- types.d.ts
Fixes #410 
This is just a dumb proposal for the issue above.
> export withTranslation as an independent function

- __tests__/hocs/app-with-translation.test.js
- src/hocs/app-with-translation.js
> fix: Use asPath for dynamic client side routing

- __tests__/hocs/app-with-translation.test.tsx
- src/hocs/app-with-translation.tsx
> fix: Only call router.replace when lang has changed

- __tests__/hocs/app-with-translation.test.tsx
- src/hocs/app-with-translation.tsx
> fix: Memory leak regression

- README.md
> docs: Update accessing current language section

- __tests__/middlewares/next-i18next-middleware.test.ts
- src/middlewares/next-i18next-middleware.ts
> fix: dont call next on redirect

- .circleci/config.yml
> feat: target multiple nodejs versions in circleci

- .npmignore
> chore: Add tsconfig to npmignore

- __tests__/middlewares/next-i18next-middleware.test.ts
- examples/simple/__tests__/e2e/locale-subpaths-foreign.test.js
- src/middlewares/next-i18next-middleware.ts
Fixes #497. Fixes #469.
Adds an e2e test to prevent regressions and updates middleware unit tests.
> fix: Modify middleware approach to fix 404s

- .gitignore
- __tests__/middlewares/next-i18next-middleware.test.ts
This PR refactors middleware tests and removes all the internal mocks
> feat(middleware): Refactor middleware tests

- __tests__/middlewares/next-i18next-middleware.test.ts
- src/middlewares/next-i18next-middleware.ts
> fix(bug): update lng query param on subpath change

- __tests__/middlewares/next-i18next-middleware.test.ts
- examples/simple/yarn.lock
- src/middlewares/next-i18next-middleware.ts
> fix: Do not ignore routes at i18nextMiddleware level

- __tests__/config/create-config.test.ts
- src/config/create-config.ts
> fix: removes duplicate languages

- .eslintrc
- README.md
- examples/simple/__tests__/e2e/router-hooks-and-hoc.test.js
- examples/simple/i18n.js
- examples/simple/pages/use-router.js
- examples/simple/pages/with-router.js
- examples/simple/public/static/locales/de/use-router.json
- examples/simple/public/static/locales/de/with-router.json
- examples/simple/public/static/locales/en/use-router.json
- examples/simple/public/static/locales/en/with-router.json
- src/hocs/index.ts
- src/hocs/with-router.tsx
- src/hooks/index.ts
- src/hooks/use-router.tsx
- src/index.ts
- src/router/wrap-router.ts
- types.d.ts
Fix #316
Before updating the README, maybe @isaachinman you can tell me if the rest looks good to you :)
> feat: Add useRouter and withRouter

- README.md
- __tests__/config/create-config.test.ts
- __tests__/config/test-helpers.ts
- __tests__/hocs/app-with-translation.test.tsx
- src/config/default-config.ts
- src/hocs/app-with-translation.tsx
- types.d.ts
Continuation of #509 . Rebased onto master. 
Conflicts are resolved and tests are passing.
> feat: Make shallowRender configurable

- examples/simple/yarn.lock
- package.json
- src/middlewares/next-i18next-middleware.ts
- src/utils/lng-from-req.ts
- types.d.ts
- yarn.lock
> chore: Upgrade i18next-express-middleware

- package.json
- yarn.lock
> fix: i18next-http-middleware cookie bug

- README.md
- examples/simple/i18n.js
fixes #687 
Modified the example app and the instructions so that they can be used without modification in any environment.
> fix: Modified the example app and the instructions as per issue 687

- types.d.ts
> fix: add localeExtension to InitConfig type

- README.md
- __tests__/types.test.tsx
- src/index.ts
- types.d.ts
> feat: Add I18nContext

- README.md
> docs: Update next export note

- src/config/create-config.ts
- types.d.ts
> fix: handling of backend options if using with other backends

- babel.config.json
- package.json
tree-shaking & module concatenation
> feat: Add an ESM entry point to allow better bundle optimizations

- README.md
Due
https://github.com/isaachinman/next-i18next/issues/814#issuecomment-688382104
> docs: Adds useTranslation hook example of usage

- src/config/createConfig.ts
use @cescoallegrini modifications from
https://github.com/isaachinman/next-i18next/pull/934
in order to port them to the beta version
> fix: Make create-config defaultFile use localeStructure

- src/config/createConfig.test.ts
- src/config/createConfig.ts
- src/serverSideTranslations.ts
> fix: Add server side loading of fallbackLng

- package.json
- src/config/defaultConfig.ts
- yarn.lock
> refactor: Add react-i18next useSuspense

- src/serverSideTranslations.test.ts
- src/serverSideTranslations.ts
> fix: Restore getAllNamespaces functionality

- .npmignore
> fix: Ship src dir to support TypeScript types

- README.md
> docs: Update sponsors section

- package.json
- src/appWithTranslation.client.test.tsx
- src/appWithTranslation.server.test.tsx
- src/appWithTranslation.tsx
- src/config/createConfig.test.ts
- src/config/createConfig.ts
- src/createClient/browser.test.ts
- src/createClient/browser.ts
- src/createClient/node.test.ts
- src/createClient/node.ts
- src/serverSideTranslations.test.ts
- src/serverSideTranslations.ts
- tsconfig.json
- types.d.ts
- yarn.lock
> refactor: Enable TypeScript strict mode

- src/createClient/node.test.ts
- src/createClient/node.ts
> fix: create i18next clone to fix #1063

- src/createClient/node.ts
fixes #1101 by creating a clone always from the first instance of i18next.
> fix: resolve memory leak, by cloning always from the main instance

- README.md
Update text in the README.md according to this [issue](https://github.com/isaachinman/next-i18next/issues/1097)
This might help when search the doc with `docker` keyword and find the solution.
> docs: Update README Dockerfile

- examples/simple/yarn.lock
- package.json
- yarn.lock
* update react-i18next to 11.8.13 to fix [CVE-2021-23346](https://github.com/i18next/react-i18next/issues/1275)
> Fix CVE-2021-23346 vulnerability

- README.md
> docs: Update README with interpolation format example

- README.md
- docs/v8-migration.md
Sorry I accidentally delete my fork I added this new PR
This is an exact copy of the previous PR https://github.com/isaachinman/next-i18next/pull/1238
PLUS I added the requested docs folder and connected the README as requested by @isaachinman
> fix: issue-#1040

- src/serverSideTranslations.test.ts
- src/serverSideTranslations.ts
Fixes #1267.
cc @Nikoms @ktml.
> fix: serverSideTranslations loading all locales

- README.md
- src/serverSideTranslations.ts
This PR is to address #1052 where an empty array for requiredNamespaces returns all namespaces instead of none. 
This is my first PR so please let me know what is missing and what I can add to get this merged in 😄
> fix: Issue #1052

- src/appWithTranslation.tsx
- https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level
> refactor: Move hook out of condition

- .circleci/config.yml
- examples/simple/yarn.lock
- package.json
- src/appWithTranslation.client.test.tsx
- src/appWithTranslation.tsx
- src/serverSideTranslations.test.tsx
- src/serverSideTranslations.ts
- src/types.ts
- yarn.lock
> refactor: v9

- package.json
> fix: Pin i18next-fs-backend

- README.md
> docs: note for asynchronous backends

- package.json
- yarn.lock
> chore: Bump i18next to v21.5.3

- package.json
- src/config/createConfig.test.ts
- src/config/defaultConfig.ts
> refactor: Remove interpolation from defaultConfig

- README.md
- examples/simple/yarn.lock
- src/config/createConfig.test.ts
- src/config/createConfig.ts
- src/serverSideTranslations.test.tsx
- src/serverSideTranslations.ts
- src/types.ts
> feat: Allow function type for localePath

- src/appWithTranslation.client.test.tsx
- src/appWithTranslation.tsx
> fix: Respect configOverride.resources

- package.json
- yarn.lock
> chore: Upgrade react-i18next

- src/appWithTranslation.tsx
- src/serverSideTranslations.test.tsx
- src/serverSideTranslations.ts
- src/types.ts
> fix: Pass namespaces to the client, closes #1839

- README.md
Just a doc update to widen use-cases for the localePath example. Might help to reduce issues in the future.
Related context
- https://github.com/i18next/next-i18next/issues/1552#issuecomment-991786093
- https://github.com/bryantobing12/layout-reproduce-i18next/pull/1#pullrequestreview-1149156994
> docs: widen scenario for custom localePath example

- .size-limit.cjs
Just a simple post-it note... So nobody wonders
> Size limit comment for maintainers

- TROUBLESHOOT.md
If you agree, I'd like to initiate a troubleshoot guide.
As example I've *naïvely* added material from https://github.com/i18next/next-i18next/issues/1917#issuecomment-1285401978
> docs: initial TROUBLESHOOT guide

- package.json
Those resolutions aren't useful anymore it seems
> chore: cleanup internal obsolete resolutions

- .eslintrc.json
- examples/simple/pages/second-page.tsx
I feel it make sense, feel free to discard
> feat(example): add getServerSideProp in secondPage

- README.md
just correct example url, please check
thanks!
> chore: correct example url

- TROUBLESHOOT.md
> [Troubleshoot] add a link

- TROUBLESHOOT.md
Based on https://github.com/i18next/next-i18next/discussions/2029#discussioncomment-4184481
> docs: reword troubleshoot

- TROUBLESHOOT.md
Based on https://github.com/i18next/next-i18next/issues/1917#issuecomment-1320966835. Thx @spyhere
> docs: improve troubleshoot docs

- TROUBLESHOOT.md
Hi,
given the previous context (in Line 73), I think you meant `react-i18next` here.
Thanks.
> possibly a typo

- package-lock.json
- package.json
Hey just upgrade to 12.1.5 to resolve https://github.com/i18next/react-i18next/issues/1543
Included in https://github.com/i18next/react-i18next/pull/1606
> Update: react-i18next to 12.1.5

- examples/simple/pages/_app.tsx
Fixing a typo who is creating a broken link.
> Fix typo and broken link

- TROUBLESHOOT.md
> docs: fix extraneous file extension

- TROUBLESHOOT.md
Based on https://github.com/i18next/next-i18next/issues/2115#issuecomment-1464711030. Fix https://github.com/i18next/next-i18next/issues/2115
> docs: improve package manager troubleshoot

- examples/simple/package.json
- examples/ssg/package.json
@adrai If you feel so, this could be merged.
BTW thanks for all your work ! Appreciated
> chore(examples): deps to latest

- examples/simple/pages/index.tsx
> fix: incorrect link

- README.md
> docs: add type to exported config in example

- package-lock.json
When installing the last version with npm 9, a new lock was produced. Seems legit to me.
> fix: refresh lock file

- README.md
> docs: update README.md typo

- README.md
This PR adds a section to the readme explaining how to mitigate the double `useEffect` issue on all `fallback: true/'blocking'` ssg pages caused by `next-i18next`.
This is described at length in [this issue](https://github.com/i18next/next-i18next/issues/2236).
> doc: add a section on fallback ssg pages in the readme

- README.md
> Fix Spelling mistake
